language: node_js
node_js:
- '9'
cache:
  directories: node_modules
before_script:
- npm run build
after_success:
- npm run coveralls
env:
  global:
  - secure: 0XAT4SlW3hmt/arCKnOrfOm26h9LGjm95Tp00LKfumwXPl2rKjos4d6s20U0tNclriKSoN2ArldDJH0/Y7cfQ6tBX3XTMJdOHdTTeY+YE6/CLavliuZZwzQxOg6hix7a8e0cmdgd6eFRL6w93YFJVwpreJqIRBHOm/HxaYfHmdHE5poepyoujXDdSA8YHhTCmIV90IsXE1IofnGkf+cNL1GXIZCTInM9Dh/7vighMSHNBYX3Cm/4LwXHB4USfYbPPZKnpPV3lb5xDukgNYaQNmSjhgTo1PYL28tX00NijY6bNadbctGfIGvl+evqywji/lM/p9nCNxskjin0r/fsGhYKmVtZLF2InOlLJK55Vq/hAtKixD4E5KyvrNMmccJvIE4xTS/6hGEQNknqe8RhK4RpXObFgj2yrtpGOloZr2Mna713kDExRyG23eNzUJghs6kLEpjxJ7mQ9PX8TaiaFqf7g23vbe5jYDEyyFcXBO/LMgDHIV2W0WLfPtxk7P3V1jGVz1DjNKdov1xB++qWiQrpgnpnJCqpYN3FW4V7NfrKTJjZLesldJjhuqPyjqut4nGy/mC+DnOGX64/14og9K6d8VGOMUJYBehTxylMvidAh9nreyHJYiDai62SJK3qu449yejaaX6fV1Og8hhh90JiMbEzglATFOR1fjdfWyk=
  - secure: XVV1baz0XCjpm6H0EfP7onZze0jtcyBxavm7CH39gtLAi2eDY65cojJWN93mXWQSvTfYN5Qenkw6JX5eSB4R17asRFiYDt2Uge8H2rb7wWWUbHHtozam0t+Cu2yJzblUmwPOcUFTo30Lz69HC4KyYA2HxOpRQlF7PHzn3rjCb5yGzstQKEXHcueV6Uho3e2P1Hs5aF8g1TchBIeX/qP/qJIdYWheIpOCGIdEr6/9idCZv9kMYlRqCh0gnBg7Oas0tQeRpx1zHrElYeWDVBzFGJq6gMETf/mXs43y2suqgk4iLCEK0qOBhJOLUsS3be9Hm3SBGRE0qs2Wx1YuMMD0u1qoeJe9Z8RgLrDP2/7D9x9MuC3lyNzB/9Pmve/81VBG6pCG6t7c6kWqai0MfHaciqkiZPI73+rjrXjQuImOzn4iotEaMs6VJLg1hGOPbfxy6Qb+xfW0451CJ+50EKAmPJNoBNYYywt0v0IB6EW+X16IEtl+sXZywo3UqQQAyFTcjQ82UW+a62uHwoAfomsf24JUi0AeeiCdyuOA2CyVwBq7Ia+qHDOp071HWCZauT/6UU2ZbGeOX7Nr1AGe7h/jKgP7Nm2caItScjq0f3SGixH19suW/beJeQw/Jy+w6wqnTdv+RIHOR09voPNmGq/MuqRjcsPWm9keLygWlqWdhV4=
