FROM node:alpine
LABEL maintainer="Leonardo Habitzreuter <leo.habitzreuter@gmail.com>"
ENV NODE_ENV=development
ENV dbUrl=mongodb://leonardo:sysadmin@ds125588.mlab.com:25588/churrasco
ENV authSecret=skjdhf6$$%dojkhfˆsdkjhf
COPY . /app
WORKDIR /app
RUN npm i -g pm2 && npm install
EXPOSE 3001
CMD ["pm2", "start", "configs/pm2.dev.json", "--no-daemon"]