FROM node:alpine
LABEL maintainer="Leonardo Habitzreuter <leo.habitzreuter@gmail.com>"
ENV NODE_ENV=development
ENV dbUrl=mongodb://leonardo:sysadmin@ds125588.mlab.com:25588/churrasco
ENV authSecret=skjdhf6$$%dojkhfˆsdkjhf
COPY . /app
WORKDIR /app
RUN npm install
EXPOSE 3001
CMD [ "npm", "start" ]